version: '3.8'
networks:
  dendromap-api:
    driver: bridge
    external: true
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
services:
  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.retention.time=30d'
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      #- ./data:/prometheus
    restart: unless-stopped
    networks:
      - dendromap-api
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '8080:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - dendromap-api
  loki:
    image: grafana/loki:2.9.0  # Use the latest version
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config:/etc/loki
      - ./loki-data/tmp:/tmp/loki
    user: root
    networks:
      - dendromap-api

  promtail:
    image: grafana/promtail:2.9.0  # Use the latest version
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config:/etc/promtail
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - dendromap-api

    #password: root123
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    networks:
      - dendromap-api
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    command:
      - '-port=8098'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    networks:
      - dendromap-api
  nest-backend:
    image: sahbanial/dendromap-mobile-api:staging
    container_name: nest-backend
    pid: host
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - '8090:8090'
    volumes:
      - ../public:/usr/src/app/public
      - ./env:/usr/src/app/env
      - /var/log:/var/log
    networks:
      - dendromap-api
